### ISSUE TITLE
    how can get "&#x002A;  &pt456;  &#x2502;  &#x03AF;  &#x397;" in your generated xml seed 20.xml   

### ISSUE THREAD

**Issue by ZkmStudio** [zhunki/skyfire#1]
in function  visitChardata , your program do not get the chardata's content,how can get chardata such as "&#x002A;  &pt456;  &#x2502;  &#x03AF;  &#x397;" in your generated xml seed 20.xml   

visitChardata (XMLParser.ChardataContext ctx) {
		String parent = "null", grandparent = "null", greatparent = "null", sibling = "null";
		if (ctx.getParent() != null) {
			parent = ctx.getParent().getClass().getSimpleName();
			if (ctx.getParent().getParent() != null) {
				grandparent = ctx.getParent().getParent().getClass().getSimpleName();
				if (ctx.getParent().getParent().getParent() != null) {
					greatparent = ctx.getParent().getParent().getParent().getClass().getSimpleName();
				}
			}
			if (ctx.getParent().getChild(0) != null) {
				// sibling = ctx.getParent().getChild(0).getClass().getSimpleName();
			}
		}
		String rule = "<" + greatparent + "," + grandparent + "," + parent + "," + sibling + ">";
		rule += ctx.getClass().getSimpleName() + "->";
		if (ctx.getChildCount() > 0 && ctx.getChildCount() < XMLPCSGLearner.maxChildCount) {
			for (int i = 0; i < ctx.children.size(); i++) {
				if (ctx.getChild(i).getClass().getSimpleName().equals("TerminalNodeImpl")) {
				            **_rule += " ";_**
				} else {
					rule += "@@@@@" + ctx.getChild(i).getClass().getSimpleName() + "#####";
				}
			}
		} else {
			return visitChildren(ctx);
		}

**Comment by zhunki** [comment]
you can use 
rule += ctx.getChild(i).getText().length() > XMLPCSGLearner.maxChildLength
							? ctx.getChild(i).getText().substring(0, XMLPCSGLearner.maxChildLength).trim()
							: ctx.getChild(i).getText().trim();
to collect some chardata, but chardata is not so important to grammar and collecting too much chardata    will cause the datatbase too large. Therefore, I will choose not to collect chardata during learning a large corpus.

**Comment by ZkmStudio** [comment]
ok , i got it . thank you !
